config/routes.rb
Rails.application.routes.draw do
  
  devise_for :admins, path: 'admins', controllers: { sessions: "admins/sessions"}
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount Blazer::Engine, at: "blazer"

  get 'home/index', to: 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'home#index'

  get 'home/residential', to: 'home#residential'
  get 'home/commercial', to: 'home#commercial'
  get 'quotes/new', to: 'quotes#new'

  post 'quotes/new', to: 'quotes#create'

  get 'leads', to: 'leads#new'
  post '', to: 'leads#create'

  get 'admins/sign_in', to: 'sessions#new'
  
  resources :quotes


  resources :leads


end

app/models/address.rb
class Address < ApplicationRecord
    
    belongs_to :customer, optional: true
    belongs_to :building, optional: true
    
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/battery.rb
class Battery < ApplicationRecord

    has_many :columns, dependent: :destroy

    belongs_to :building, optional:true
    belongs_to :employee, optional: true
end

app/models/building.rb
class Building < ApplicationRecord

    belongs_to :customer, optional: true
    
    has_one :address
    has_one :building_detail, dependent: :destroy
    has_many :batteries, dependent: :destroy

 

end

app/models/building_detail.rb
class BuildingDetail < ApplicationRecord

    belongs_to :building, optional:true 

    has_settings do |s|
        s.key :information
    end
end

app/models/column.rb
class Column < ApplicationRecord
    belongs_to :battery, optional: true 

    has_many :elevators, dependent: :destroy
end

app/models/customer.rb
class Customer < ApplicationRecord

    belongs_to :user, optional: true
    
    has_one :address
    has_many :buildings, dependent: :destroy
end

app/models/elevator.rb
class Elevator < ApplicationRecord

    belongs_to :column, optional: true
end

app/models/employee.rb
class Employee < ApplicationRecord
    # Include default devise modules. Others available are:
    # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
    devise :database_authenticatable, :registerable,
           :recoverable, :rememberable
  
    has_many :batteries, dependent: :destroy
  end
  

app/models/lead.rb
class Lead < ApplicationRecord
 
    has_one_attached :image

end

app/models/quote.rb
class Quote < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :email, :password])
        devise_parameter_sanitizer.permit(:account_update, keys: [:username, :firstname, :lastname, :email, :password, :current_password])
    end 

    def require_admin
        # depending on your auth, something like...
        redirect_to root_path unless current_admin
      end
end

app/controllers/concerns/accessible.rb
module Accessible
    extend ActiveSupport::Concern
    included do
      before_action :check_user
    end
  
    protected
    def check_user
      if current_admin
        flash.clear
        # if you have rails_admin. You can redirect anywhere really
        redirect_to(rails_admin.dashboard_path) and return
      elsif current_admin
        flash.clear
        # The authenticated root path can be defined in your routes.rb in: devise_scope :user do...
        redirect_to(authenticated_user_root_path) and return
      end
    end
  end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
  def residential
  end

  def commercial
  end
  def new
  end
  
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController

    before_action :set_lead, only: [:show, :edit, :update, :destroy]
    def new
    @lead = Lead.new
    end
    def create
       

        @lead = Lead.new()

        @lead.contactFullName = params['ContactName']
        @lead.companyName = params['CompanyName']
        @lead.Email = params['Email']
        @lead.phone = params['Phone']
        @lead.projectName = params['ProjectName']
        @lead.projectDescription = params['Description']
        @lead.department = params['Department']
        @lead.message = params['Message']
        @lead.attachedFile = params[:Attachment]

        @lead.save!
    end

    def index
        @lead = Lead.all
    end 






    
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController  

    before_action :set_quote, only: [:show, :edit, :update, :destroy]
    def new
        @quote = Quote.new
    end
           
    def create

        buildingType = params['buildingType']

        @quote = Quote.new()
        
        @quote.buildingType = buildingType
        
    
    
        if buildingType == 'residential'
          @quote.apartmentNumbers = params['esidentialApartmentNumbers']
          @quote.numberOfFloors = params['ResidentialNumberOfFloors']
          @quote.numberOfBasements = params['ResidentialNumberOfBasements']

          @quote.estimatedCagesNeeded = params['estimatedCagesNeeded']
          @quote.packageSelection = params['packageSelection']
        
          @quote.elevatorPrice =  params['elevatorPrice']
          @quote.installationCost = params['installationCost']
          @quote.totalPrice = params['totalPrice']
          
          @quote.save!
         

      
        end
    
        if buildingType == 'commercial'
          @quote.numberOfFloors = params['CommercialNumberOfFloors']
          @quote.numberOfStores = params['CommercialNumberOfStores']
          @quote.numberOfBasements = params['CommercialNumberOfBasements']
          @quote.numberCages = params['CommercialNumberCages']
          @quote.parkingLevels = params['CommercialParkingLevels']
    
          @quote.estimatedCagesNeeded = params['estimatedCagesNeeded']
          @quote.packageSelection = params['packageSelection']
         
          @quote.elevatorPrice =  params['elevatorPrice']
          @quote.installationCost = params['installationCost']
          @quote.totalPrice = params['totalPrice']
       
          @quote.save!
         
          
      
        end
    
        if buildingType == 'corporate'
          @quote.numberOfCompanies = params['CorporateNumberOfCompanies']
          @quote.numberOfFloors = params['CorporateNumberOfFloors']
          @quote.numberOfBasements = params['CorporateNumberOfBasements']
          @quote.parkingLevels = params['CorporateParkingLevels']
          @quote.occupantsPerFloor = params['CorporateOccupantsPerFloor']
    
          @quote.estimatedCagesNeeded = params['estimatedCagesNeeded']
          @quote.packageSelection = params['packageSelection']
       
          @quote.elevatorPrice =  params['elevatorPrice']
          @quote.installationCost = params['installationCost']
          @quote.totalPrice = params['totalPrice']
           
          @quote.save!
         
        end
    
        if buildingType == 'hybrid'
          @quote.numberOfStores = params['HybridNumberOfStores']
          @quote.numberOfFloors = params['HybridNumberOfFloors']
          @quote.numberOfBasements = params['HybridNumberOfBasements']
          @quote.parkingLevels = params['HybridParkingLevels']
          @quote.occupantsPerFloor =  params['HybridOccupantsPerFloor']
      
    
          @quote.estimatedCagesNeeded = params['estimatedCagesNeeded']
          @quote.packageSelection = params['packageSelection']
       
          @quote.elevatorPrice =  params['elevatorPrice']
          @quote.installationCost = params['installationCost']
          @quote.totalPrice = params['totalPrice']
       
          @quote.save!
         

        end
        
    end  

  def index
      @quote = Quote.all
  end  


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  
<script> var plugin_path = 'assets/javascripts' </script>
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

<%= csrf_meta_tags %>

<meta charset="utf-8" />
<title>Rocket Elevators</title>
<meta name="description" content="" />


    
  
  

    <!-- mobile settings -->
    <meta
      name="viewport"
      content="width=device-width, maximum-scale=1, initial-scale=1, user-scalable=0"/>
 
    <!-- WEB FONTS : use %7C instead of | (pipe) -->
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600%7CRaleway:300,400,500,600,700%7CLato:300,400,400italic,600,700"
      rel="stylesheet"
      type="text/css"/>

</head>
<body class = "enable-animation" style="wide">
  
      <div id="wrapper">
      <!-- 
				AVAILABLE HEADER CLASSES
				Default nav height: 96px
				.header-md 		= 70px nav height
				.header-sm 		= 60px nav height
				.b-0 		= remove bottom border (only with transparent use)
				.transparent	= transparent header
				.translucent	= translucent header
				.sticky			= sticky header
				.static			= static header
				.dark			= dark header
				.bottom			= header on bottom
				
				shadow-before-1 = shadow 1 header top
				shadow-after-1 	= shadow 1 header bottom
				shadow-before-2 = shadow 2 header top
				shadow-after-2 	= shadow 2 header bottom
				shadow-before-3 = shadow 3 header top
				shadow-after-3 	= shadow 3 header bottom
				.clearfix		= required for mobile menu, do not remove!
				Example Usage:  class="clearfix sticky header-sm transparent b-0"
			-->
      <div id="header" class="navbar-toggleable-md fixed-top header-md clearfix" style = "position: fixed;">
        <!-- TOP NAV -->
        <header id="topNav">
          <div class="container">
            <!-- Mobile Menu Button -->
            <button
              class="btn btn-mobile"
              data-toggle="collapse"
              data-target=".nav-main-collapse"
            >
              <i class="fa fa-bars"></i>
            </button>

            <!-- Logo -->
            <a class="logo float-left" >
              <img
                src="/assets/rocket/R2.png"
                alt=""
                style="width: 200px; height: 70px"
              />
            </a>

            <!-- 
							Top Nav 
							
							AVAILABLE CLASSES:
							submenu-dark = dark sub menu
						-->
            <div
              class="navbar-collapse collapse float-right nav-main-collapse submenu-dark"
            >
              <nav class="nav-main">
                <!-- 
									.nav-onepage
									Required for onepage navigation links
									
									Add .external for an external link!
								-->
                <ul
                  id="topMain"
                  class="nav nav-pills nav-justified nav-onepage"
                >
                  <li class="active">
                    <!-- HOME -->
                    <%= link_to 'Home',root_path, method: :get %>
                  </li>
                  <li>
                    <!-- SERVICES -->
                    <%= link_to "Services" , home_index_path(anchor: 'services'), method: :get %>
                  </li>
                  <li>
                    <!-- WORK -->
                    <%= link_to "Work" , home_index_path(anchor: 'work'), method: :get %>
                  </li>
                  <li>
                    <!-- NEWS -->
                    <%= link_to "News" , home_index_path(anchor: 'news'), method: :get %>
                  </li>
                  <li>
                    <!-- CLIENTS -->
                    <%= link_to "Clients" , home_index_path(anchor: 'clients'), method: :get %>
                  </li>
                  <li>
                    <!-- CONTACT -->
                    <%= link_to "Contact" , home_index_path(anchor: 'contact'), method: :get %>
                  </li>
                 
                  <li>
                    <!-- ADMIN -->
                    <a href="#slidetop"> Admin </a>
                    <ul class="dropdown-menu">
                        <% if admin_signed_in? %>
                          <li><%= link_to "Backdoor", rails_admin.dashboard_path, method: :get %></li>
                          <% else %>
                          <li><%= link_to "Login", admins_sign_in_path , method: :get %></li>
                          
                        <% end %>
                        <% if admin_signed_in? %>
                          <li role="separator" class="divider"></li>
                          <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
                        <% end %>
                      </ul>
                      
                  </li>
                   
                </ul>
              </nav>
            </div>
          </div>
        </header>
        <!-- /Top Nav -->
      </div>  

      <%= yield %>

   
  </body>


</html>